export type Country = 'US' | 'UK' | 'Singapore' | 'India';
export type BGVStatus = 'Cleared' | 'Pending' | 'In Progress' | 'Overdue';
export type RecruitmentStatus = 'Applied' | 'In Review' | 'Interviewing' | 'Offered' | 'Rejected';

export interface Employee {
  employee_id: string;
  firstname: string;
  lastname: string;
  startdate: string;
  exitdate: string;
  title: string;
  businessunit: string;
  employeestatus: string;
  departmenttype: string;
  division: string;
  state: string;
  performance_score: string;
  current_employee_rating: number;
  application_date: string;
  education_level: string;
  years_of_experience: number;
  desired_salary: number;
  job_title: string;
  recruitment_status: RecruitmentStatus;
  survey_date: string;
  engagement_score: number;
  satisfaction_score: number;
  work_life_balance_score: number;
  flight_risk: 'Low Risk' | 'Medium Risk' | 'High Risk';
  country: Country;
  bgv_agency: string;
  bgv_status: BGVStatus;
  bgv_days_elapsed: number;
  bgv_sla_days: number;
  bgv_at_risk: 'Yes' | 'No';
  onboarding_type: string;
  laptop_assigned: 'Yes' | 'No';
  day0_completed: 'Yes' | 'No';
  orientation_completed: 'Yes' | 'No';
  harassment_policy: 'Yes' | 'No';
  ai_ethics: 'Yes' | 'No';
  gemini_training: 'Yes' | 'No';
  figma_training: 'Yes' | 'No';
  asana_onboarded: 'Yes' | 'No';
  days_since_joining: number;
  onboarding_complete: 'Yes' | 'No';
  modules_completed: number;
  compliance_pct: number;
}
